server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
      name: wex-app-transaction
  datasource:
    url: jdbc:mysql://localhost:3306/wexdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      import_files: "classpath:schema.sql"
    defer-datasource-initialization: true

  exchange-rate-api:
    url: 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange'
